version: '0.2'
ignorePaths:
    - '**/.husky/'
    - '**/.task-output/'
    - '**/.wireit/'
    - '**/node_modules/'
    - '**/pnpm-lock.yaml'
dictionaryDefinitions: []
dictionaries: []
words:
    - Ourchitecture
    - expressjs
    - resave
    - syscall
    - todos
    - typeof
    - todomvc
    - wireit
ignoreWords:
    - davidanson
    - EACCES
    - EADDRINUSE
    - MADR
    - nvmrc
    - pnpmrc
import: []
